In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import re
import random
import networkx as nx
from tqdm import tqdm
from scipy.sparse import coo_matrix
import community as community_louvain
from collections import defaultdict
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics.pairwise import cosine_similarity
from gensim.models import Word2Vec


RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)
random.seed(RANDOM_STATE)


df1 = pd.read_parquet('/COS_bert_word_embed.parquet', engine='pyarrow').set_index('word')
df1.columns = df1.index

df2 = pd.read_parquet('/COS_bert_word_topic_sim.parquet', engine='pyarrow').set_index('word')
df2.columns = df2.index

df3 = pd.read_parquet('/COS_lda_word_topic_prob.parquet', engine='pyarrow').set_index('word')
df3.columns = df3.index


# 단어 순서 섞어주기
words_shuffled = df1.index.tolist()
random.shuffle(words_shuffled)
df1 = df1.loc[words_shuffled, words_shuffled]
df2 = df2.loc[words_shuffled, words_shuffled]
df3 = df3.loc[words_shuffled, words_shuffled]

# 0 제거
df1[df1 < 0] = 0
df2[df2 < 0] = 0
df3[df3 < 0] = 0

In [2]:
df1

word,인수,주민,당부,시작,오픈,부동산,조사,거리,소양,확인,...,필기,기대감,콘텐츠들,논란,디자이너,사건,생태,수용,검사,단위
word,,,,,,,,,,,,,,,,,,,,,
인수,1.000000,0.541406,0.507308,0.472583,0.473823,0.581587,0.534695,0.522558,0.540198,0.553875,...,0.508920,0.509450,0.529675,0.541946,0.320746,0.604996,0.467637,0.645286,0.585428,0.587589
주민,0.541406,1.000000,0.570825,0.526697,0.542195,0.555448,0.498983,0.688470,0.525100,0.499364,...,0.470233,0.457991,0.466474,0.544115,0.401015,0.588249,0.487998,0.634791,0.579447,0.572093
당부,0.507308,0.570825,1.000000,0.795518,0.781408,0.311606,0.614614,0.647435,0.808878,0.679231,...,0.759584,0.713520,0.608712,0.791186,0.401627,0.781552,0.559033,0.792817,0.915404,0.880810
시작,0.472583,0.526697,0.795518,1.000000,0.836717,0.354838,0.643685,0.642839,0.752404,0.650187,...,0.716414,0.628271,0.602129,0.685909,0.482552,0.743516,0.575202,0.796253,0.831817,0.824569
오픈,0.473823,0.542195,0.781408,0.836717,1.000000,0.419047,0.662757,0.680031,0.746594,0.713503,...,0.713203,0.648431,0.652714,0.662274,0.470910,0.715201,0.544438,0.818933,0.838245,0.813813
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
사건,0.604996,0.588249,0.781552,0.743516,0.715201,0.461017,0.756028,0.664084,0.769845,0.725260,...,0.752393,0.621071,0.661452,0.844978,0.404333,1.000000,0.574340,0.829690,0.851174,0.802924
생태,0.467637,0.487998,0.559033,0.575202,0.544438,0.412737,0.607777,0.471815,0.654214,0.507253,...,0.603708,0.470822,0.564290,0.547516,0.426452,0.574340,1.000000,0.633406,0.598780,0.610064
수용,0.645286,0.634791,0.792817,0.796253,0.818933,0.523545,0.771250,0.726361,0.823405,0.753617,...,0.774813,0.672431,0.730234,0.756806,0.535329,0.829690,0.633406,1.000000,0.898137,0.883254
검사,0.585428,0.579447,0.915404,0.831817,0.838245,0.398506,0.781845,0.712172,0.852308,0.806575,...,0.819014,0.698756,0.655785,0.810735,0.468925,0.851174,0.598780,0.898137,1.000000,0.913562
단위,0.587589,0.572093,0.880810,0.824569,0.813813,0.446602,0.699934,0.749105,0.844760,0.722705,...,0.796731,0.667394,0.653407,0.776759,0.513023,0.802924,0.610064,0.883254,0.913562,1.000000

In [3]:
df2

word,인수,주민,당부,시작,오픈,부동산,조사,거리,소양,확인,...,필기,기대감,콘텐츠들,논란,디자이너,사건,생태,수용,검사,단위
word,,,,,,,,,,,,,,,,,,,,,
인수,1.000000,0.940580,0.957046,0.955293,0.961912,0.965609,0.975411,0.951870,0.962734,0.979099,...,0.963539,0.974907,0.962671,0.962435,0.937669,0.961095,0.981178,0.973855,0.968326,0.965205
주민,0.940580,1.000000,0.985124,0.977232,0.978340,0.935714,0.961982,0.994006,0.977742,0.969484,...,0.978551,0.979593,0.962122,0.983974,0.931679,0.986431,0.970955,0.975798,0.981640,0.980420
당부,0.957046,0.985124,1.000000,0.997099,0.995266,0.926233,0.972337,0.991695,0.995954,0.989588,...,0.994386,0.983516,0.981243,0.992468,0.950378,0.992491,0.983015,0.989691,0.997851,0.996913
시작,0.955293,0.977232,0.997099,1.000000,0.997907,0.926024,0.976964,0.989579,0.996724,0.989364,...,0.990059,0.981048,0.988608,0.990510,0.965102,0.991295,0.985689,0.993259,0.997967,0.998679
오픈,0.961912,0.978340,0.995266,0.997907,1.000000,0.935519,0.980584,0.991681,0.997310,0.993655,...,0.988616,0.980527,0.991763,0.989423,0.970891,0.990696,0.987031,0.996994,0.998280,0.998374
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
사건,0.961095,0.986431,0.992491,0.991295,0.990696,0.954146,0.986886,0.994290,0.988539,0.982201,...,0.990757,0.992518,0.981910,0.998409,0.957405,1.000000,0.990840,0.989367,0.993190,0.992758
생태,0.981178,0.970955,0.983015,0.985689,0.987031,0.962835,0.994348,0.981254,0.985588,0.986883,...,0.979891,0.991253,0.989729,0.990807,0.969002,0.990840,1.000000,0.993503,0.989749,0.990670
수용,0.973855,0.975798,0.989691,0.993259,0.996994,0.949901,0.988603,0.987828,0.994051,0.993897,...,0.983073,0.982566,0.995352,0.988914,0.979894,0.989367,0.993503,1.000000,0.995636,0.996851
검사,0.968326,0.981640,0.997851,0.997967,0.998280,0.937667,0.981928,0.992408,0.998385,0.995452,...,0.994332,0.986214,0.988620,0.992467,0.961820,0.993190,0.989749,0.995636,1.000000,0.999025
단위,0.965205,0.980420,0.996913,0.998679,0.998374,0.937248,0.982368,0.990678,0.997471,0.992825,...,0.990032,0.984920,0.990793,0.992048,0.969545,0.992758,0.990670,0.996851,0.999025,1.000000

In [4]:
df3

word,인수,주민,당부,시작,오픈,부동산,조사,거리,소양,확인,...,필기,기대감,콘텐츠들,논란,디자이너,사건,생태,수용,검사,단위
word,,,,,,,,,,,,,,,,,,,,,
인수,1.000000,0.032004,0.010651,0.415731,0.446905,0.021511,0.160405,0.686984,0.007641,0.311857,...,0.256135,0.404895,0.172377,0.216009,0.233732,0.227239,0.154294,0.204037,0.312030,0.074286
주민,0.032004,1.000000,0.429965,0.459525,0.033279,0.134845,0.258561,0.026889,0.006785,0.506301,...,0.140652,0.040978,0.016656,0.658410,0.023224,0.050095,0.030270,0.331305,0.173265,0.430703
당부,0.010651,0.429965,1.000000,0.363826,0.035222,0.305466,0.041287,0.014444,0.004898,0.037360,...,0.021665,0.013211,0.013046,0.067122,0.019815,0.092059,0.030155,0.156785,0.385036,0.413728
시작,0.415731,0.459525,0.363826,1.000000,0.420835,0.238163,0.371908,0.557323,0.021550,0.501826,...,0.268455,0.465251,0.311324,0.490934,0.466255,0.360742,0.348420,0.467956,0.396418,0.492052
오픈,0.446905,0.033279,0.035222,0.420835,1.000000,0.080906,0.107215,0.310356,0.055925,0.247340,...,0.661838,0.408560,0.135487,0.108862,0.119268,0.161286,0.113130,0.263062,0.148711,0.188158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
사건,0.227239,0.050095,0.092059,0.360742,0.161286,0.055618,0.245749,0.388288,0.007674,0.163175,...,0.148395,0.384505,0.138755,0.375089,0.140825,1.000000,0.119602,0.499868,0.270319,0.391314
생태,0.154294,0.030270,0.030155,0.348420,0.113130,0.066485,0.228348,0.321029,0.064924,0.271808,...,0.039032,0.204655,0.616105,0.111887,0.138559,0.119602,1.000000,0.253673,0.433674,0.191318
수용,0.204037,0.331305,0.156785,0.467956,0.263062,0.067761,0.269849,0.271860,0.008421,0.431997,...,0.223767,0.253178,0.034440,0.384388,0.427454,0.499868,0.253673,1.000000,0.395348,0.606826
검사,0.312030,0.173265,0.385036,0.396418,0.148711,0.125267,0.095300,0.408073,0.010272,0.172660,...,0.049824,0.243363,0.060440,0.163647,0.090290,0.270319,0.433674,0.395348,1.000000,0.341584
단위,0.074286,0.430703,0.413728,0.492052,0.188158,0.156332,0.444390,0.124054,0.005403,0.450426,...,0.192420,0.251771,0.103468,0.375314,0.172521,0.391314,0.191318,0.606826,0.341584,1.000000

# Make Graph!

## individual graphs

# threshold 없음

In [5]:
# 함수: 유사도 행렬 → 단일 그래프 생성
def create_graph_from_df(df, label):
    G = nx.Graph()
    words = df.index.tolist()
    G.add_nodes_from(words)
    
    for i, word_i in tqdm(enumerate(df.index), total=len(df), desc=f"Creating {label}"):
        for j in range(i + 1, len(df.columns)):
            word_j = df.columns[j]
            weight = df.iat[i, j]
            G.add_edge(word_i, word_j, weight=weight, type=label)
    
    return G

# 개별 그래프 생성
G1 = create_graph_from_df(df1, 'sim1')
G2 = create_graph_from_df(df2, 'sim2')
G3 = create_graph_from_df(df3, 'sim3')

# 결과 출력
print(f"G1 (sim1) - 노드 수: {G1.number_of_nodes()}, 엣지 수: {G1.number_of_edges()}")
print(f"G2 (sim2) - 노드 수: {G2.number_of_nodes()}, 엣지 수: {G2.number_of_edges()}")
print(f"G3 (sim3) - 노드 수: {G3.number_of_nodes()}, 엣지 수: {G3.number_of_edges()}")

Creating sim1: 100%|██████████| 2597/2597 [00:32<00:00, 81.01it/s]
Creating sim2: 100%|██████████| 2597/2597 [00:32<00:00, 79.72it/s]
Creating sim3: 100%|██████████| 2597/2597 [00:33<00:00, 78.29it/s]

G1 (sim1) - 노드 수: 2597, 엣지 수: 3370906
G2 (sim2) - 노드 수: 2597, 엣지 수: 3370906
G3 (sim3) - 노드 수: 2597, 엣지 수: 3370906

In [6]:
# 모든 weight 값 추출
weights = [data['weight'] for _, _, data in G1.edges(data=True)]

# 통계값 계산
print(f"엣지 개수: {len(weights)}")
print(f"최소 weight: {np.min(weights)}")
print(f"최대 weight: {np.max(weights)}")
print(f"평균 weight: {np.mean(weights):.2f}")
print(f"중앙값 weight: {np.median(weights)}")
print(f"표준편차: {np.std(weights):.2f}")

엣지 개수: 3370906
최소 weight: 0.0
최대 weight: 0.9958657439066876
평균 weight: 0.60
중앙값 weight: 0.6054310913910537
표준편차: 0.17

In [7]:
# 모든 weight 값 추출
weights = [data['weight'] for _, _, data in G2.edges(data=True)]

# 통계값 계산
print(f"엣지 개수: {len(weights)}")
print(f"최소 weight: {np.min(weights)}")
print(f"최대 weight: {np.max(weights)}")
print(f"평균 weight: {np.mean(weights):.2f}")
print(f"중앙값 weight: {np.median(weights)}")
print(f"표준편차: {np.std(weights):.2f}")

엣지 개수: 3370906
최소 weight: 0.0883820220823126
최대 weight: 0.9999488179664748
평균 weight: 0.98
중앙값 weight: 0.984784873535886
표준편차: 0.03

In [8]:
# 모든 weight 값 추출
weights = [data['weight'] for _, _, data in G3.edges(data=True)]

# 통계값 계산
print(f"엣지 개수: {len(weights)}")
print(f"최소 weight: {np.min(weights)}")
print(f"최대 weight: {np.max(weights)}")
print(f"평균 weight: {np.mean(weights):.2f}")
print(f"중앙값 weight: {np.median(weights)}")
print(f"표준편차: {np.std(weights):.2f}")

엣지 개수: 3370906
최소 weight: 0.0005424193774261279
최대 weight: 0.999999508369228
평균 weight: 0.19
중앙값 weight: 0.1265978945886176
표준편차: 0.18

## 각 그래프에 대한 community detection

In [9]:
def get_louvain_partition(G, label, res):
    partition = community_louvain.best_partition(G, weight='weight', resolution=res, random_state=RANDOM_STATE)
    return pd.DataFrame(list(partition.items()), columns=['word', f'community_{label}'])

df_comm1 = get_louvain_partition(G1, 'sim1', 1.2) # 1.2
df_comm2 = get_louvain_partition(G2, 'sim2', 1.1) # 1.01
df_comm3 = get_louvain_partition(G3, 'sim3', 3.3) # 3.3 

print(f"sim1 커뮤니티 수: {df_comm1['community_sim1'].nunique()}")
print(f"sim2 커뮤니티 수: {df_comm2['community_sim2'].nunique()}")
print(f"sim3 커뮤니티 수: {df_comm3['community_sim3'].nunique()}")

sim1 커뮤니티 수: 821
sim2 커뮤니티 수: 2550
sim3 커뮤니티 수: 626

In [10]:
# 단어 기준 병합
df_merged = df_comm1.merge(df_comm2, on='word').merge(df_comm3, on='word')
df_merged = df_merged.set_index('word')

In [11]:
df_merged

      community_sim1  community_sim2  community_sim3
word
인수                 0               0              58
주민                 1               1             290
당부                 2               2             509
시작                 3               3               3
오픈                 4               4               4
...              ...             ...             ...
사건               498            2546             592
생태               156            2547             518
수용               789            2548             480
검사                29            2549             175
단위               303            1493             474

[2597 rows x 3 columns]

In [12]:
import gc

del df_comm1, df_comm2, df_comm3, G1, G2, G3
gc.collect()

23052

# Vectorize

## OneHotEncoder (Best)

In [13]:
encoder = OneHotEncoder(sparse_output=False)  
community_vectors = encoder.fit_transform(df_merged)
pd.DataFrame(community_vectors, index=df_merged.index)

,0,1,2,3,4,5,6,7,8,9,...,3987,3988,3989,3990,3991,3992,3993,3994,3995,3996
word,,,,,,,,,,,,,,,,,,,,,
인수,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
주민,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
당부,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
시작,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
오픈,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
사건,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
생태,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
수용,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
검사,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
단위,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
encoder = OneHotEncoder(sparse_output=False)  
community_vectors = encoder.fit_transform(df_merged)
community_vectors = pd.DataFrame(community_vectors, index=df_merged.index)

sim_matrix = cosine_similarity(community_vectors.values)

G_cluster = nx.Graph()
words = community_vectors.index.tolist()
G_cluster.add_nodes_from(words)

threshold = 0.3 
for i in tqdm(range(len(words)), desc="Building new graph"):
    for j in range(i + 1, len(words)):
        sim = sim_matrix[i, j]
        if sim >= threshold:
            G_cluster.add_edge(words[i], words[j], weight=sim)


print(f"G_cluster - 노드 수: {G_cluster.number_of_nodes()}, 엣지 수: {G_cluster.number_of_edges()}")

Building new graph: 100%|██████████| 2597/2597 [00:00<00:00, 3517.07it/s]

G_cluster - 노드 수: 2597, 엣지 수: 122992

In [15]:
# 모든 weight 값 추출
weights = [data['weight'] for _, _, data in G_cluster.edges(data=True)]

# 통계값 계산
print(f"엣지 개수: {len(weights)}")
print(f"최소 weight: {np.min(weights)}")
print(f"최대 weight: {np.max(weights)}")
print(f"평균 weight: {np.mean(weights):.2f}")
print(f"중앙값 weight: {np.median(weights)}")
print(f"표준편차: {np.std(weights):.2f}")

엣지 개수: 122992
최소 weight: 0.3333333333333334
최대 weight: 1.0000000000000002
평균 weight: 0.34
중앙값 weight: 0.3333333333333334
표준편차: 0.04

In [16]:
pd.DataFrame(weights)[0].value_counts()

0
0.333333    121228
0.666667      1757
1.000000         7
Name: count, dtype: int64

# Community Detection

In [17]:
res_range = np.arange(3.0, 3.1, 0.1)

resolutions = [round(x, 1) for x in res_range]

resolution_results = {}  # 결과 저장용 딕셔너리

for res in tqdm(resolutions, desc="Louvain by resolution"):
    print(f"\n================ Resolution: {res:.1f} ================")

    partition = community_louvain.best_partition(G_cluster, weight='weight', resolution=res, random_state=RANDOM_STATE)
    num_communities = len(set(partition.values()))

    community_groups = defaultdict(list)
    for node, comm_id in partition.items():
        community_groups[comm_id].append(node)

    community_groups = dict(sorted(community_groups.items(), key=lambda x: len(x[1]), reverse=True))

    # 결과 저장
    resolution_results[res] = {
        'num_communities': num_communities,
        'communities': community_groups
    }

    print(f"총 커뮤니티 수: {num_communities}")

Louvain by resolution:   0%|          | 0/2 [00:00<?, ?it/s]

================ Resolution: 3.0 ================

Louvain by resolution:  50%|█████     | 1/2 [00:00<00:00,  1.19it/s]

총 커뮤니티 수: 168

================ Resolution: 3.1 ================

Louvain by resolution: 100%|██████████| 2/2 [00:01<00:00,  1.19it/s]

총 커뮤니티 수: 168

In [18]:
def print_communities_by_resolution(res):
    print(f"\n Resolution: {res}")
    result = resolution_results.get(res)
    
    if result is None:
        print("해당 resolution 값의 결과가 없습니다.")
        return

    print(f"총 커뮤니티 수: {result['num_communities']}")
    
    for comm_id, words in result['communities'].items():
        print(f"\nCommunity {comm_id} ({len(words)}개 단어)")
        print(', '.join(words))

In [19]:
print_communities_by_resolution(3.0)

 Resolution: 3.0
총 커뮤니티 수: 168

Community 0 (134개 단어)
인수, 부동산, 대기업, 가격, 얼마, 저작권, 혁신적, 몸값, 영업, 홍보, 상용, 수집, 경제적, 기업가치, 자금, 투자금, 계약서, 크레딧, 게재, 사업자, 자본, 저장, 예약, 제품, 결제, 제조, 자원, 점유율, 창업, 산업현장, 사용률, 부문장, 복지, 공장, 기업가, 지급, 효율성, 식당, 가치, 효율, 고객, 수요, 보험, 자본주의, 마케팅, 금융, 보수, 창업자, 제조업, 품질, 성장, 금액, 성장세, 고객사들, 매출, 혁신, 유통, 경영학, 지속가능, 영업이익, 벤처, 수익률, 계산, 지역균형발전, 효율화, 자회사, 주식, 산업혁명, 투자, 카드, 계정, 매출액, 업그레이드, 기업들, 혁신상, 쇼핑, 비용, 거래, 경제성, 사업화, 상점, 요금, 수익화, 수익, 용량, 상품, 보급, 특허, 재정, 지원사업, 개척, 매장, 효율적, 예산, 수익성, 농업, 스토어, 비즈니스, 계약, 가치관, 맛집, 기업간거래, 공급, 업계, 수출, 임금, 중소기업, 은행, 판매자, 이코노미, 서점, 절약, 재산, 생산, 산업, 투자유치, 사업, 고객들, 상거래, 마켓, 생산성, 판매, 산업계, 냉장고, 교환, 회사들, 연평균, 구매, 소비자, 사용량, 사업부, 배송, 소비, 투자자

Community 5 (124개 단어)
조사, 인류, 우리말, 재난, 부모, 응답, 최종, 이동, 디바이드, 마지막, 태도, 월드, 약점, 인간, 오늘날, 외교, 문명, 탄소, 사장, 퍼포먼스, 주권, 중소, 수도, 진입, 근로자, 가족들, 지수, 국회, 독특, 전시장, 초래, 보고서, 묘사, 불평등, 협의회, 학위, 상승, 시사, 하위, 증가, 이래, 추가적, 소득, 영웅, 설명, 종료, 위기, 수입, 박사, 사무실, 분리, 자율주행, 과거, 제외, 세계관, 지향, 자동차, 숫자, 시민들, 민주주의, 노동, 직종, 시위, 컨텐츠, 마무리, 방한, 팬덤, 평등, 대책, 자산, 설명회, 패권, 진학, 복합, 얘기, 연봉, 완화, 경찰, 안정, 평균, 의원, 거부, 확정, 동화, 연구진, 상징, 촉구, 정기, 추세, 경제, 개혁, 이민자, 계층, 포부, 자녀, 회원, 단체, 물가, 비율, 장기, 파괴, 구사, 가량, 청년들, 배출, 요인, 대담, 상대적, 배달, 주년, 지위, 석사, 상위, 취득, 학력, 기점, 커리어, 응원, 구입, 사태, 수치, 장관, 비결, 나라

Community 106 (112개 단어)
캡처, 웹사이트, 프로그램, 가상공간, 공학, 챗봇, 인터넷, 장비, 데이터센터, 프로그래밍, 디지털화, 소셜미디어, 휴대폰, 안드로이드, 자동화, 가상세계, 소프트웨어, 기기, 프로그래머, 자동, 기술적, 하드웨어, 통합검색, 채널, 업로드, 체제, 팟캐스트, 설정, 동영상, 인터랙티브, 필터링, 체계, 파일, 출현, 기계, 설치, 배터리, 신청, 라디오, 스마트폰, 멀티미디어, 블록체인, 이용자, 전기차, 오픈소스, 가상인간, 통신사, 정보통신기술, 전기, 화면, 테크, 검색, 빅테크, 소통, 반도체, 로봇, 무선, 통신, 방송, 애플리케이션, 비디오, 노트북, 인사이트, 사이버, 실시간, 스튜디오, 네트워크, 전화, 의사소통, 데이터셋, 애드테크, 서버, 프로토타입, 드론, 센서, 콜센터, 다운로드, 사물인터넷, 연결, 인텔리전스, 모니터링, 위성, 브라우저, 인터페이스, 온라인, 운영툴, 이용자들, 컴퓨팅, 데이터베이스, 신기술, 사이트, 일각, 패드, 클라우드, 알고리즘, 자문, 모바일, 스크린, 구독자, 컴퓨터, 디지털전환, 영상, 사용자, 인프라, 장치, 기계번역, 커뮤니케이션, 가상현실, 태블릿, 공공데이터, 카메라, 녹음

Community 51 (110개 단어)
당부, 이행, 부처, 정작, 영향력, 기념사, 버튼, 지방자치, 강화, 제도적, 직원, 지정, 혁명, 직속, 책임, 부합, 유지, 특별, 지역, 정의, 균형발전, 존중, 참석, 개방성, 전시관, 사회, 골든타임, 불법, 민관, 정책, 공단, 지방, 경계, 고령, 진료, 회복, 심의, 중앙, 신뢰도, 정립, 최첨단, 안보, 블루칼라, 약속, 도지사, 위원회, 다양성, 균형, 원격, 실행력, 분권, 후속, 관람, 지속적, 결정, 주류, 은퇴, 특구, 거버넌스, 원칙, 주의, 공공, 규제, 증명, 취임, 보호, 역대, 정치, 토론, 의료, 공공기관, 기념식, 특례, 출범, 숙련, 자치, 내국인, 유치, 마스터플랜, 인재들, 재원, 전형, 차별, 권한, 진흥, 특별법, 중요시, 회의, 종합계획, 종합, 가족, 장려, 배려, 민주, 국민, 인원, 방침, 가사, 지방정부, 필수, 독립, 단지, 민간, 참관, 대기, 청사진, 서비스형, 관리사, 생존, 장악

Community 21 (110개 단어)
대회, 참가자, 청소년, 실수, 안전, 토크, 러닝, 교실, 공감대, 사고, 프롬프트, 교육청, 맞춤, 참가, 신고, 걱정, 컨퍼런스, 싸움, 조심, 상금, 관리자, 대전환, 예선, 특수학교, 순식간, 확률, 전국, 눈길, 원고, 기조, 타입, 인체, 문화적, 치수, 경진, 조기, 글로컬, 연주, 단속, 카페, 접수, 관람객들, 비판, 실패, 상장, 창의, 융합, 코칭, 각광, 엔지니어, 청소년들, 반응, 박람회, 범죄, 원리, 피아노, 지원자, 장벽, 시각화, 문제점, 거주, 안정적, 취약, 모양, 피해, 에세이, 문제들, 본선, 체험존, 음악, 학부모, 재창작, 교육감, 일상생활, 경진대회, 고등부, 세대, 게시, 공포, 수원, 축구, 지리적, 위험, 어려움, 혼란, 파급력, 개최, 고등학교, 작곡, 영어교육, 수여, 중등, 다음달, 조종, 미래교실, 확산, 조명, 중학생, 관찰, 안착, 폭발적, 다큐, 도모, 힌트, 의식, 원인, 업종, 부상, 도내, 워크숍

Community 16 (105개 단어)
소식, 헬스케어, 해설, 챌린지, 집단, 획득, 진짜, 대한민국, 우위, 여행, 주기, 관광, 제재, 출신, 주목, 호응, 의학, 차례, 수석, 열기, 선수, 시행착오, 플레이, 호텔, 스포츠, 국제, 재단, 부정적, 시각, 정도, 통합, 대응, 추가, 헬스, 승리, 연간, 사항, 표현력, 산업군, 목록, 이날, 부사장, 선진, 남녀, 조회수, 소리, 통제, 리서치, 보유, 컨트롤, 프라이버시, 전후, 멀티, 멀티모달, 차단, 관광객, 디렉터, 협회, 할루시네이션, 경기, 접속, 저비용, 주체, 그랜드, 총괄, 해킹, 여부, 조정, 기법, 신속, 요약, 예시, 그동안, 답변, 시니어, 당장, 상태, 예외, 지분, 신뢰, 제어, 염두, 청년, 잠재, 자격증, 삭감, 규칙, 물류, 체계적, 에이전트, 이력서, 고령화, 세상, 수렴, 다국어, 완벽, 대체, 지침, 입지, 국제적, 선도자, 수행, 출시, 우리나라, 필기

Community 4 (101개 단어)
오픈, 파트너십, 편의, 코딩, 복습, 최신, 순위, 특성, 지시문, 범용, 유형, 가능, 성능, 구조화, 벤치마크, 구동, 자리, 그중, 질의응답, 활용도, 편의성, 주변, 감각, 화학, 개방, 크기, 싱크탱크, 사내, 용도, 카테고리, 사용법, 문서, 사원, 일상적, 한마당, 추론, 연구개발, 전작, 덕분, 차이, 유익, 부모님, 쿼리, 학계, 이용, 최적화, 기여, 온디바이스, 입력, 활용법, 수업사례, 주인공, 자기주도, 차별점, 공격, 작동, 법률, 시행, 적용, 응용, 자기주도학습, 목적, 마크, 보장, 그룹, 확신, 안전성, 실제, 주기적, 외부, 확보, 동의, 사용성, 처리, 효과적, 진실, 전력, 연말, 비교, 자연어, 베타, 종합적, 입증, 벤치, 부스, 절감, 가속, 동일, 코드, 메모리, 취약점, 신뢰성, 공정, 점수, 적합, 사용, 촉발, 별도, 차지, 경량화, 경량

Community 20 (93개 단어)
공개, 점프스타트, 무료, 열풍, 겨울, 이중, 순차적, 이외, 도시, 스트레스, 인스트럭션, 변화, 결합, 소셜, 규모, 매력적, 구분, 기초, 사전, 발판, 차량, 위주, 소방, 동력, 전용, 바람, 유료, 관리툴, 향상, 매개변수, 치매, 언어모델, 파트너들, 종류, 새해, 민원, 유명, 최고, 소장, 기본, 진도, 게임사, 브랜드, 개인별, 적응, 명칭, 전송, 전문지식, 바이오, 모델들, 허브, 대비, 전환, 러시아, 지사, 편리, 출생, 도메인, 우수, 실현, 소형, 머신러닝, 실질적, 급변, 권위, 무분별, 독창성, 협업, 직접적, 사회적, 중형, 이중언어, 자체, 양질, 이달, 아트, 최선, 게임, 유사, 서부, 응대, 선별, 편집, 초기, 교육업체들, 화재, 메이커, 이력, 교육업, 비상, 시민, 내달, 기후

Community 132 (90개 단어)
소양, 성취, 노출, 프로젝트, 체크, 자기, 사례집, 포함, 성향, 지도안, 게시물, 기준, 서비스들, 정착, 각종, 노트, 요소, 다짐, 스타, 인성, 명령, 교육과정, 전자책, 문제해결, 거짓, 물론, 연계성, 메뉴, 조작, 명시, 메모, 자료, 개정, 노동자들, 게이미피케이션, 탐지, 사례, 앵커, 사례들, 교원, 출연, 과학, 도우미, 인성교육, 공부법, 구체, 유초등, 설계, 본인, 드라이브, 탑재, 실행, 재해, 안내, 학급, 타인, 성취기준, 유해, 대두, 리포트, 충격, 결국, 삭제, 폭력, 초등, 통계, 가짜, 법안, 워터마크, 능가, 해고, 악용, 말씀, 얼굴, 실천, 선거, 연계, 놀이, 노동자, 장착, 일반인, 정시, 자료실, 교과, 허위, 유포, 일반인들, 함양, 가짜뉴스, 것들

Community 70 (90개 단어)
상담실, 버추얼, 지속, 전파, 가상, 파트너, 만족도, 엔진, 음성합성, 대사, 일환, 필요성, 상호, 일상, 스터디, 플러스, 중요성, 아이돌, 필수적, 성공적, 즉각적, 이름, 소속, 유학, 외국인, 실생활, 원활, 증대, 일례, 행동, 인생, 차별성, 계기, 특화, 추출, 교류, 상호작용, 활성화, 상담, 발화자, 심리, 작용, 대학, 촉진, 비판적, 연습, 시범, 음성인식, 동작, 시간, 고도화, 단축, 유선, 관심사, 상무, 학기, 핵심, 소요, 문자화, 매력, 생활, 상대, 대학교, 생명, 케이팝, 속도감, 역할, 장기적, 신제품, 본격화, 마을, 가공, 팝업, 자극, 체류, 일관, 자리매김, 콘텐트, 피드백, 스트리트, 모임, 관계자들, 대학생, 중요, 소개팅, 시티, 애니메이션, 통번역, 활동, 고충

Community 11 (89개 단어)
법무, 메일, 관내, 물음, 전면, 고등학생, 친밀, 형식, 퀴즈, 누적, 개월, 제휴, 요구, 체험학습, 키오스크, 조금, 성인, 동식물, 병행, 견인, 입법, 심화, 어린이, 최소, 체험, 투입, 공룡, 비속어, 아바타, 페이지, 우주, 한편, 달성, 조립, 프로필, 예비, 창출, 환경, 체험공간, 선제적, 몰입도, 어린이들, 법원, 마이, 만남, 캠프, 가입자, 고교, 영역, 학점, 캐릭터들, 진로, 비중, 요청, 호기심, 판결, 목격, 차시, 단순, 대표적, 능동적, 재직, 자사, 초대, 노동력, 니즈, 건수, 신규, 전개, 설문, 한정, 빈도, 다양화, 건전, 고도, 도전, 마이룸, 공간, 합성어, 동물, 돌파, 제정, 욕설, 방학, 판사, 유토피아, 키즈, 진화, 비서

Community 50 (89개 단어)
충돌, 눈앞, 출간, 갈등, 박물관, 개인적, 언팩, 엔터, 정체성, 문자, 만화, 종교, 국민들, 핵심적, 선두, 개인, 독창적, 활용성, 전쟁, 진보, 어르신들, 원동력, 장르, 자체적, 수식, 파트너사, 미션, 독자적, 정서, 고령층, 문학, 사상, 독서, 호평, 풀이, 긴장, 입사, 중시, 후보, 동네, 작품, 판독, 상식, 영토, 겨냥, 자율, 지배, 스토리텔링, 친절, 사기, 유저, 작가, 유로, 매개, 개인화, 정보기술, 창작물, 감정, 작가들, 오답, 엔터테인먼트, 자랑, 울트라, 성별, 오랫동안, 대규모언어모델, 스스로, 변수, 가전, 독자들, 직전, 역사적, 집계, 정답, 무장, 웨어러블, 공감, 대답, 공존, 출판, 소설, 후기, 중동, 철학, 장애, 레시피, 노인, 분쟁, 멤버

Community 36 (86개 단어)
성격, 혼자, 축제, 가명, 대국민, 의견, 장관상, 맞춤법, 연애, 전시, 유망, 성황리, 소재, 창의성, 행사장, 저작자, 불편, 방문, 댓글, 투명, 머리, 버튜버, 도구, 장애인, 공로, 동기, 기분, 안정성, 요리, 나머지, 페스티벌, 직원들, 메타버스, 크리에이터들, 저작물, 상상력, 버스, 관람객, 전시회, 참여, 개막, 공모, 분위기, 체험관, 창의력, 공모전, 로고, 인턴, 참가자들, 초보자, 권리, 자신감, 설립, 몰입감, 제작, 예술, 인상, 조망, 느낌, 도서관, 게시판, 원래, 디자인, 사랑, 행사, 파일럿, 재료, 아티스트, 크리에이터, 윤리성, 창작, 형태, 초청, 격려, 마음, 천재, 패턴, 웹툰, 감사, 감독, 일주일, 창의적, 공익, 광학문자인식, 저작, 모방

Community 25 (86개 단어)
시청자, 부여, 연령, 기억, 마스터, 유출, 취향, 여름, 정식, 개시, 버즈, 시리즈, 탄생, 증강, 효과음, 문장, 가정, 실장, 선착순, 드로잉, 자연, 배치, 브로드, 교정, 커버, 두려움, 학습효과, 친구, 발화, 유치원, 인구, 사옥, 현상, 캐릭터, 레벨, 단어, 가입, 업데이트, 어휘력, 길이, 감상, 이벤트, 발달, 영단어, 참여자, 프리토킹, 프리, 첫선, 방문객, 인물, 학습법, 공식, 아이스크림, 발음, 아이, 흥미, 탐험, 론칭, 차세대, 날씨, 토킹, 대화, 실력, 초등학생, 교육업계, 자유, 스피킹, 성취감, 플랜, 스토리, 아이들, 효과, 실감, 북클럽, 나이, 분량, 직업, 회화, 학습자, 소수, 등장인물, 확장현실, 원어민, 시청, 영어회화, 플레이어

Community 33 (83개 단어)
원서, 차별화, 가이드북, 지도, 공동체, 세션, 커넥트, 건설, 편향, 교직원, 투명성, 오프라인, 브리핑, 공공성, 연관성, 원천, 미팅, 임팩트, 얼라이언스, 내비게이션, 멤버십, 움직, 밀착, 인권, 동참, 배움터, 투어, 긍정, 클럽, 윤리, 재현, 개소, 프로덕트, 종사자, 시설, 라인업, 물건, 이직, 직장인, 화상, 커뮤니티, 외연, 접목, 집약, 측위, 출처, 광고주, 선언, 협력, 도덕, 창작자, 메인, 공유, 적자, 실과, 직장인들, 리더, 책임성, 집행, 콘퍼런스, 트래픽, 초개인화, 방과, 시나리오, 트윈, 상반기, 지역사회, 도구들, 범위, 전산, 빌딩, 아동, 책임감, 실내, 근본, 분기, 측면, 원천기술, 조성, 탐색, 의도, 콘텐츠들, 생태

Community 63 (80개 단어)
이론, 다각도, 활약, 재학생, 양성, 일반적, 학부, 두각, 주간, 인재, 표준, 신설, 충족, 편입생, 최다, 강사진, 실습, 경력, 개편, 육성, 주행, 시상식, 취업, 보통, 인력, 자격, 이수, 전공, 재편, 성공사례, 심층, 해외, 경영, 모델링, 국방, 포트폴리오, 교수진, 정규, 개설, 영입, 모듈, 중순, 총장, 인증, 개교, 모집, 학사, 현업, 장학금, 트렌드, 마케터, 국외, 교육생, 바우처, 교내, 원년, 신입, 진출, 네트워킹, 교육비, 원장, 수립, 직무, 재학, 대행, 실무, 학과, 인턴십, 멘토링, 매칭, 선발, 스트리밍, 캠퍼스, 장학, 프로세스, 전액, 학문, 졸업, 유수, 혜택

Community 8 (79개 단어)
확인, 위험성, 선진국, 킬러, 논쟁, 노력, 간과, 시범학교, 개념, 질의, 이해, 필자, 주장, 창조, 일자리, 학원, 반복적, 연사, 사고력, 설문조사, 지혜, 시도, 평소, 축소, 암기, 표절, 과학자, 플러그인, 고수, 당국, 증강현실, 심포지엄, 저자, 논리, 입체, 대안, 해석, 사정, 제출, 근본적, 연구자들, 가을, 여정, 대입, 배제, 국어, 교육학, 나름, 직면, 위협, 전문가들, 출제, 실험, 시험, 인식, 윤리적, 편견, 자율적, 검증, 사실, 범용적, 교육계, 수능, 전체적, 초록, 긍정적, 문해력, 일상화, 수험생, 의장, 운용, 저명, 연구자, 부작용, 잠재력, 테스트, 인용, 비유, 콘셉트

Community 1 (77개 단어)
주민, 근거, 실물, 심사, 유도, 디지털교과서, 침해, 일정, 발행사, 대시보드, 현황, 특수교육, 전략, 합의, 저하, 절차, 서책, 반대, 무리, 학습데이터, 시연, 교과서, 학령, 억양, 해결책, 단계적, 철저, 학부모들, 시중, 패널, 성취도, 통과, 확충, 법령, 작문, 중학교, 학년, 제기, 솔루션, 공무원, 특수, 선도, 정비, 점검, 일대일, 접근, 구독, 규정, 개인정보, 과도, 시제품, 현실화, 개별, 맞춤형, 경로, 검정, 정보, 표시, 미만, 기본법, 강자, 학생별, 개발사, 글씨, 외산, 도움, 여론, 각자, 구독료, 지자체, 중독, 경고, 가구, 출판사, 단계, 문법, 논란

Community 43 (77개 단어)
시작, 등록, 결과, 광고, 급증, 수상, 국립, 경쟁력, 빌더, 이사, 준비, 성공, 여성, 우수성, 어젠, 추정, 경쟁, 획기적, 선정, 최우수상, 클릭, 수강생, 급성장, 채택, 기자간담회, 수강, 전당, 첫걸음, 최적, 승부, 보상, 발명, 엣지, 인기, 사물, 성과, 개선, 홈페이지, 수상자, 금상, 타이틀, 링크, 완성, 친숙, 키워드, 자막, 공연, 분류, 어시스턴트, 라이브, 접근성, 문구, 착수, 캠페인, 감성, 경쟁사, 해커톤, 강좌, 무대, 분들, 질병, 팬데믹, 퀄리티, 포털, 발전, 극대, 블로그, 소상공인, 정확도, 안녕, 광고비, 인플루언서, 소외, 연산, 장점, 한류, 결과적

Community 9 (75개 단어)
에듀, 적정, 공부, 강의, 과목, 컨설턴트, 번역, 초중등, 학업, 교재, 미적분, 모의고사, 내신, 페어, 경험, 스쿨, 교육자료, 아카데미, 단원, 코스, 코스웨어, 기념, 보조교사, 특강, 클래스, 신입생, 원도심, 이러닝, 교육자, 평생, 등급, 고등, 전문성, 인터뷰, 강의실, 파견, 입학, 교육현장, 총회, 부진, 훈련, 학년도, 추천, 수년, 복수, 불안, 초등학교, 교과목, 입시, 현직, 간담회, 사교육, 성적, 인강, 주주, 실전, 다차원, 에듀테크, 의무, 개정안, 공교육, 학습자들, 합격, 학생들, 트랙, 산학, 컨설팅, 졸업생, 풀타임, 교수, 입학설명회, 커리큘럼, 전문가, 주말, 수학

Community 29 (74개 단어)
거리, 한마디, 메시지, 움직임, 용어, 절대적, 보안, 모빌리티, 거론, 방향성, 합성, 인사, 연기, 임원, 성우, 논의, 배우, 더빙, 지시, 수록, 연속, 번역기, 감지, 상대방, 추진, 텍스트, 이메일, 무궁무진, 조합, 구성원, 일반, 청구, 통화, 가속화, 물결, 대규모, 촬영, 변환, 거대언어모델, 대본, 운동, 음성, 출력, 노래, 말투, 목소리, 속도, 흐름, 행위, 글자, 표현, 이어폰, 추적, 의미, 보안성, 날개, 표정, 댄스, 도서, 모션, 언어장벽, 스크립트, 어휘, 메신저, 교수들, 타이어, 구성원들, 휴머노이드, 부정, 야기, 행보, 소스, 웹페이지, 채팅

Community 10 (66개 단어)
지리, 가늠, 내재, 오디오, 근무, 국장, 인문학, 표창, 하이브리드, 항공, 포럼, 하이퍼스케일, 한반도, 컨택, 공통, 로드맵, 협약, 증진, 사회학, 지평, 자국어, 터보, 한국판, 유용, 객관성, 원본, 영예, 프로, 측정, 폐쇄, 전수, 부정확, 정원, 통역사, 트레이닝, 기록, 교육기관, 지표, 사유, 보편, 케이크, 로컬, 명령어, 추후, 계열, 온프레미스, 문항, 이공, 방지, 연구팀, 해양, 주관, 매뉴얼, 채점, 전반적, 논술, 기획자, 조교, 양상, 구도, 광범위, 상담원, 객관적, 사내망, 평가, 음원

Community 102 (65개 단어)
반등, 유니버스, 자국, 관리, 종이, 신약, 경영자, 문헌, 운영, 편향성, 종목, 유산, 경영진, 사활, 배분, 복귀, 관계자, 클래스팅, 스마트, 작성, 조직, 리스크, 침투, 신경망, 주가, 리더십, 본부, 작업, 토대, 여지, 의심, 발언, 현실, 반복, 종속, 불가능, 오류, 이익, 무한, 난제, 음식, 학회, 도달, 동시, 행정, 파워, 아내, 과외, 업무, 소송, 예전, 역설, 제조사, 국가들, 숙제, 거짓말, 동료, 지적, 모달, 능력, 매니저, 소감, 손실, 구별, 법인

Community 24 (65개 단어)
나중, 문제집, 존재, 선행, 눈동자, 탐구, 학술, 주도적, 행복, 총통, 검색엔진, 그림, 정보원, 선생님, 하이테크, 요즘, 교사, 주력, 재미, 질문, 고전, 중단, 딥러닝, 여건, 토의, 포스터, 강제, 본질, 장면, 아나운서, 이미지, 발견, 학교, 교육혁신, 배경, 양식, 전망, 자신, 체육, 친구들, 하이터치, 연수, 선생, 관측, 마당, 시선, 사진, 블록, 교사들, 발굴, 최종적, 집중, 동아리, 선도학교, 예고, 깊이, 모형, 쓸모, 신장, 풍경, 교장, 그림책, 그래픽, 사진제공, 디자이너

Community 48 (63개 단어)
운영사, 취재, 미디어, 왼쪽, 허용, 바둑, 과장, 전문적, 상담사, 위원, 기사, 강국, 인문, 수수료, 한계, 방송사, 화제, 매체, 미술, 콘서트, 영어학습, 모범, 성찰, 재구성, 센터, 언론, 언론사, 직장, 디자, 연구소, 학습공동체, 포기, 출발, 최소화, 기자들, 지원단, 감소, 중점, 신문, 정확성, 고용, 하락, 제거, 외국어, 동향, 자료집, 도출, 대중화, 부장, 조절, 보도, 극복, 중심, 멘토, 제한, 심도, 편성, 내실, 일자, 개정교육, 제약, 선점, 면접

Community 23 (56개 단어)
오피스, 쇼츠, 교양, 편집자, 지식, 강연, 순서, 발간, 현안, 리터러시, 위상, 표방, 세미나, 전통적, 기회, 시절, 실용, 강화학습, 언어학, 말뭉치, 아이디어, 백과사전, 토픽, 미래, 무시, 선택, 현대, 교육적, 백과전, 드림, 습관, 폭발, 동영, 서술, 가능성, 예측, 전통, 육박, 문맥, 머신, 업퍼바운드, 중장년층, 희망, 의지, 백과전서, 코로나, 예정, 계획, 세기, 책들, 역사, 상상, 항목, 제안, 머릿속, 기대감

Community 40 (55개 단어)
돌파구, 전무, 타깃, 학습지, 노하우, 육아, 생성형, 해양생물, 박차, 대세, 팀장, 눈높이, 시대, 프리미엄, 내년, 수주, 전년, 유아, 영어권, 공략, 국산, 낚시, 화가, 조치, 어린, 월간, 상조, 어학, 기간, 대화형, 업체들, 첨삭, 체결, 시너지, 홀맨, 사흘간, 튜터, 궁금증, 지난달, 화두, 흑자, 연내, 현지시간, 교환학생, 교육열, 하루, 현지화, 실사, 역임, 홈런, 독해, 선임, 실적, 몰입, 가칭

Community 26 (54개 단어)
서류, 좌우, 건강, 양자, 전자, 원전, 케어, 형성, 아티피셜, 팩토리, 연락, 중복, 실증, 독점, 진단, 뇌파, 정상, 의사, 엔터프라이즈, 취미, 행운, 지문, 판도, 합리적, 합류, 유리, 발행, 생태계, 난이도, 다큐먼트, 물리, 운전, 선도적, 아이템, 만족, 구축, 예방, 유일, 부품, 치료, 에너지, 스타트업들, 질환, 채용, 피카, 정제, 소모, 환자, 알파벳, 추격, 소사이어티, 업무협약, 조언, 검사

Community 28 (52개 단어)
교통, 디테일, 준수, 상용화, 근간, 내부적, 고객센터, 과금, 문의, 빅데이터, 스택, 토종, 하이퍼, 완성도, 고품질, 런칭, 무기, 거대, 버티컬, 변경, 무상, 확장성, 인정, 컴퍼니, 대중, 스킬, 환각, 출격, 대량, 커스텀, 초거대, 서치, 극대화, 병원, 그래프, 최대, 학습량, 주자, 대형, 증시, 패키지, 연동, 절반, 승인, 방탈출, 완전, 토큰, 내부, 칼로, 풀스택, 튜닝, 파라미터

Community 45 (9개 단어)
수단, 문화, 다문화, 세계, 외국, 외국인들, 국가, 세계적, 부족

Community 42 (2개 단어)
네이티브, 식별

Community 65 (2개 단어)
통역, 지점

Community 69 (2개 단어)
입장, 자세

Community 85 (2개 단어)
생각, 예상

Community 94 (2개 단어)
위치, 장소

Community 116 (2개 단어)
고민, 부담

Community 123 (2개 단어)
다수, 대다수

Community 133 (2개 단어)
구성, 구조

Community 135 (2개 단어)
드라마, 사건

Community 142 (2개 단어)
대상, 포인트

Community 30 (1개 단어)
사람

Community 35 (1개 단어)
전제

Community 38 (1개 단어)
격차

Community 41 (1개 단어)
초점

Community 49 (1개 단어)
주문

Community 52 (1개 단어)
파악

Community 53 (1개 단어)
업체

Community 54 (1개 단어)
진행

Community 57 (1개 단어)
현장

Community 60 (1개 단어)
방식

Community 64 (1개 단어)
일들

Community 66 (1개 단어)
대면

Community 67 (1개 단어)
언급

Community 71 (1개 단어)
선호

Community 73 (1개 단어)
구상

Community 76 (1개 단어)
마련

Community 78 (1개 단어)
제시

Community 80 (1개 단어)
유의미

Community 82 (1개 단어)
의문

Community 83 (1개 단어)
순간

Community 84 (1개 단어)
일종

Community 86 (1개 단어)
단점

Community 87 (1개 단어)
유입

Community 89 (1개 단어)
통찰

Community 90 (1개 단어)
방법

Community 91 (1개 단어)
연관

Community 92 (1개 단어)
초안

Community 93 (1개 단어)
방안

Community 95 (1개 단어)
특정

Community 97 (1개 단어)
강조

Community 99 (1개 단어)
독자

Community 101 (1개 단어)
점유

Community 105 (1개 단어)
스타일

Community 107 (1개 단어)
중간

Community 109 (1개 단어)
영화

Community 110 (1개 단어)
해결

Community 111 (1개 단어)
정확

Community 112 (1개 단어)
도약

Community 113 (1개 단어)
개입

Community 115 (1개 단어)
제목

Community 117 (1개 단어)
기관

Community 118 (1개 단어)
현지

Community 119 (1개 단어)
단독

Community 120 (1개 단어)
부서

Community 121 (1개 단어)
습득

Community 122 (1개 단어)
추구

Community 124 (1개 단어)
주최

Community 125 (1개 단어)
검토

Community 126 (1개 단어)
동반

Community 127 (1개 단어)
감안

Community 128 (1개 단어)
차원

Community 129 (1개 단어)
협의

Community 130 (1개 단어)
모습

Community 131 (1개 단어)
시점

Community 134 (1개 단어)
독보적

Community 137 (1개 단어)
초반

Community 138 (1개 단어)
방향

Community 139 (1개 단어)
비전

Community 140 (1개 단어)
발휘

Community 141 (1개 단어)
확장

Community 143 (1개 단어)
각국

Community 144 (1개 단어)
소개

Community 145 (1개 단어)
신경

Community 146 (1개 단어)
이야기

Community 147 (1개 단어)
축적

Community 148 (1개 단어)
조건

Community 149 (1개 단어)
산하

Community 150 (1개 단어)
의존

Community 151 (1개 단어)
특징

Community 152 (1개 단어)
전달

Community 153 (1개 단어)
대처

Community 155 (1개 단어)
조회

Community 157 (1개 단어)
신중

Community 158 (1개 단어)
뒷받침

Community 159 (1개 단어)
판단

Community 160 (1개 단어)
정리

Community 161 (1개 단어)
구애

Community 162 (1개 단어)
주도

Community 163 (1개 단어)
참고

Community 164 (1개 단어)
사람들

Community 165 (1개 단어)
기획

Community 166 (1개 단어)
제도

Community 167 (1개 단어)
고유

Community 2 (1개 단어)
등장

Community 3 (1개 단어)
체감

Community 6 (1개 단어)
개개인

Community 7 (1개 단어)
이슈

Community 136 (1개 단어)
바탕

Community 12 (1개 단어)
선포

Community 13 (1개 단어)
발생

Community 14 (1개 단어)
포괄

Community 15 (1개 단어)
영향

Community 17 (1개 단어)
취지

Community 18 (1개 단어)
패러다임

Community 19 (1개 단어)
유행

Community 22 (1개 단어)
디바이스

Community 154 (1개 단어)
사이

Community 27 (1개 단어)
전반

Community 156 (1개 단어)
가지

Community 31 (1개 단어)
해소

Community 32 (1개 단어)
수준

Community 34 (1개 단어)
역량

Community 37 (1개 단어)
전문

Community 39 (1개 단어)
주제

Community 44 (1개 단어)
적극

Community 46 (1개 단어)
유발

Community 47 (1개 단어)
경향

Community 55 (1개 단어)
수정

Community 56 (1개 단어)
보완

Community 58 (1개 단어)
보조

Community 59 (1개 단어)
고급

Community 61 (1개 단어)
첨단

Community 62 (1개 단어)
관심

Community 68 (1개 단어)
맥락

Community 72 (1개 단어)
이해도

Community 74 (1개 단어)
개국

Community 75 (1개 단어)
반영

Community 77 (1개 단어)
확대

Community 79 (1개 단어)
상황

Community 81 (1개 단어)
활성

Community 88 (1개 단어)
강사

Community 96 (1개 단어)
공동

Community 98 (1개 단어)
부탁

Community 100 (1개 단어)
모색

Community 103 (1개 단어)
치열

Community 104 (1개 단어)
정신

Community 108 (1개 단어)
수용

Community 114 (1개 단어)
단위

# Modularity

In [20]:
for i in res_range:
    partition = community_louvain.best_partition(G_cluster, weight='weight', resolution=round(i,2), random_state=RANDOM_STATE)
    modularity = community_louvain.modularity(partition, G_cluster, weight='weight')
    print(f"resolution:{round(i,2)}", "->", f"Modularity: {modularity:.4f}")

resolution:3.0 -> Modularity: 0.6101
resolution:3.1 -> Modularity: 0.6101

In [ ]:
import json

modularity_scores = {
    "modularity": community_louvain.modularity(community_louvain.best_partition(G_cluster, weight='weight', resolution=3.0, random_state=RANDOM_STATE), 
                                                   G_cluster, weight='weight'),
}

with open("/meta_community_bert_word_topic_change_.json", "w") as f:
    json.dump(modularity_scores, f, indent=4)

print("Modularity scores saved.")

# Coherence

In [ ]:
import pickle

# 불러오기
with open("/tokenized_docs.pkl", "rb") as f:
    tokenized_docs = pickle.load(f)

# Save Coherence

In [ ]:
import json
from gensim.models.coherencemodel import CoherenceModel
from gensim.corpora import Dictionary

# 원하는 resolution 값 지정
selected_resolution = 3.0

# resolution 결과에서 커뮤니티 단어 리스트 추출
communities = resolution_results[selected_resolution]['communities']

# 10개 미만 커뮤니티 제외
filtered_communities = [words for words in communities.values() if len(words) >= 10]

# Dictionary 및 Corpus 생성
dictionary = Dictionary(tokenized_docs)
corpus = [dictionary.doc2bow(text) for text in tokenized_docs]

# 다양한 coherence metric 계산
coherence_scores = {}
metrics = ['c_v', 'u_mass', 'c_uci', 'c_npmi']
for metric in metrics:
    cm = CoherenceModel(
        topics=filtered_communities,
        texts=tokenized_docs,
        corpus=corpus if metric in ['u_mass'] else None,
        dictionary=dictionary,
        coherence=metric
    )
    coherence_scores[metric] = cm.get_coherence()


try:
    
    w2v_model = Word2Vec(tokenized_docs, vector_size=100, window=5, min_count=2, workers=4, epochs=10,  seed=RANDOM_STATE)

    cm_w2v = CoherenceModel(
        topics=filtered_communities,
        texts=tokenized_docs,
        dictionary=dictionary,
        coherence='c_w2v',
        keyed_vectors=w2v_model.wv
    )
    coherence_scores['c_w2v'] = cm_w2v.get_coherence().astype('float64')

except Exception as e:
    print("Word2Vec coherence 계산 실패:", e)
    coherence_scores['c_w2v'] = None


output_path = f"/meta_community_bert_word_topic_change_1.json"
with open(output_path, "w") as f:
    json.dump(coherence_scores, f, indent=4)

print(f"Coherence scores saved to {output_path}")

coherence_scores